version: '3.4'
services:

  database:
    image: postgres:12.2-alpine
    container_name: pgs
    volumes:
      - ${PWD}/volumes/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - POSTGRES_MULTIPLE_DATABASES="MySampleDDD"
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=

  rabbitmq:
    image: rabbitmq:3.8.9-management-alpine
    container_name: rmq
    ports:
      - "15672:15672"
      - "5672:5672"

  redis:
    image: redis:latest
    container_name: rds
    ports:
      - "6379:6379"

  seq:
    image: datalust/seq:2020.5
    container_name: seq
    ports:
      - "53410:80"
      - "5341:5341"
    volumes:
      - ${PWD}/volumes/seq:/data
    environment:
      - ACCEPT_EULA=Y

networks:
  default:
    driver: bridge
